AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cheesebox - One-Click AWS Setup - Creates S3 bucket, IAM user with credentials, and MediaConvert role'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Configuration'
        Parameters:
          - BucketName
          - AppDomain
    ParameterLabels:
      BucketName:
        default: 'S3 Bucket Name'
      AppDomain:
        default: 'Your App Domain'

Parameters:
  BucketName:
    Type: String
    Description: 'Unique name for your S3 bucket (lowercase, no spaces, e.g., my-private-videos-123)'
    AllowedPattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
    ConstraintDescription: 'Bucket name must be lowercase letters, numbers, and hyphens only'
    MinLength: 3
    MaxLength: 63

  AppDomain:
    Type: String
    Description: 'Your app domain for CORS (e.g., https://myapp.com or leave as localhost for testing)'
    Default: 'http://localhost:3000'

Resources:
  # S3 Bucket for video storage
  VideosBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - 'http://localhost:3000'
              - !Ref AppDomain
            ExposeHeaders:
              - Content-Length
              - Content-Range
              - ETag
            MaxAge: 3000
      VersioningConfiguration:
        Status: Suspended
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Application
          Value: Cheesebox
        - Key: ManagedBy
          Value: CloudFormation

  # MediaConvert IAM Role
  MediaConvertRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'Cheesebox-MediaConvertRole-${AWS::StackName}'
      Description: 'Allows MediaConvert to access S3 bucket for video transcoding'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: mediaconvert.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: S3BucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListBucket'
                Resource:
                  - !GetAtt VideosBucket.Arn
                  - !Sub '${VideosBucket.Arn}/*'
      Tags:
        - Key: Application
          Value: Cheesebox
        - Key: ManagedBy
          Value: CloudFormation

  # IAM User for application access
  CheeseboxUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Sub 'cheesebox-user-${AWS::StackName}'
      Tags:
        - Key: Application
          Value: Cheesebox
        - Key: ManagedBy
          Value: CloudFormation

  # IAM Policy for the user
  CheeseboxUserPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: CheeseboxUserPolicy
      Users:
        - !Ref CheeseboxUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # S3 permissions for video storage
          - Sid: S3BucketAccess
            Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:DeleteObject'
              - 's3:ListBucket'
            Resource:
              - !GetAtt VideosBucket.Arn
              - !Sub '${VideosBucket.Arn}/*'
          # MediaConvert permissions for video transcoding
          - Sid: MediaConvertAccess
            Effect: Allow
            Action:
              - 'mediaconvert:CreateJob'
              - 'mediaconvert:GetJob'
              - 'mediaconvert:DescribeEndpoints'
            Resource: '*'
          # Permission to pass MediaConvert role
          - Sid: PassRoleToMediaConvert
            Effect: Allow
            Action: 'iam:PassRole'
            Resource: !GetAtt MediaConvertRole.Arn
            Condition:
              StringEquals:
                'iam:PassedToService': 'mediaconvert.amazonaws.com'

  # Access keys for the IAM user
  UserAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName: !Ref CheeseboxUser

Outputs:
  StackName:
    Description: 'CloudFormation Stack Name'
    Value: !Ref 'AWS::StackName'
    Export:
      Name: !Sub '${AWS::StackName}-StackName'

  BucketName:
    Description: 'S3 Bucket Name - Enter this in your app settings'
    Value: !Ref VideosBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  Region:
    Description: 'AWS Region - Enter this in your app settings'
    Value: !Ref 'AWS::Region'
    Export:
      Name: !Sub '${AWS::StackName}-Region'

  AccessKeyId:
    Description: 'IAM Access Key ID - Enter this in your app settings'
    Value: !Ref UserAccessKey
    Export:
      Name: !Sub '${AWS::StackName}-AccessKeyId'

  SecretAccessKey:
    Description: 'IAM Secret Access Key - SAVE THIS NOW! You cannot retrieve it later. Enter this in your app settings.'
    Value: !GetAtt UserAccessKey.SecretAccessKey

  MediaConvertRoleArn:
    Description: 'MediaConvert Role ARN - Enter this in your app settings'
    Value: !GetAtt MediaConvertRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-MediaConvertRoleArn'

  SetupInstructions:
    Description: 'Next Steps'
    Value: 'Copy all 5 values above and paste them into your Cheesebox settings page. The Secret Access Key is shown only once - save it now!'
